import type { Metadata } from "next";

import { Suspense } from "react";

import { Inter } from "next/font/google";
import { Providers } from "@/components/Providers";
import { Analytics } from "@vercel/analytics/react";
import { GoogleTagMgr } from "@/components/GoogleTagMgr";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`bg-[#17181C] text-white ${inter.className}`}>
				<Suspense>
					<GoogleTagMgr />
					<Analytics />
				</Suspense>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
